import type { Metadata } from "next";
import './globals.css';
import { Header } from '@/app/_components/Header';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title:'Create Next blog',
  description: 'Generated by create next app',
};


export default function RootLayout({ children }: { children:React.ReactNode}) {
  return (
    <html lang='ja'>
      <body>
        <Header/>
        <main>{children}</main>
      </body>
    </html>
  );
};